constants:
  file:
    directory: D:\ParkDoheum\2025\2025-04-msa\backend\upload

spring:
  application:
    name: gallery
  datasource:
    url: jdbc:log4jdbc:mariadb://localhost/gallery
    username: root
    password: green502
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  servlet:
    multipart:
      max-file-size: 15MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml
